/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vahlrfrvjwaocnmnckdi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhaGxyZnJ2andhb2NubW5ja2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5NjUzMTUsImV4cCI6MjA5NjU0MTMxNX0.RFyOqET3J8-DyvUQd4jy0DQImXlqejGLw6waYt-tiKI"